# Generated by BudE for Convert God

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "preset",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("1080p", "1080p"),
                            ("720p", "720p"),
                            ("480p", "480p"),
                        ],
                        default="720p",
                        max_length=16,
                    ),
                ),
                ("input_key", models.CharField(max_length=512)),
                ("input_size_bytes", models.BigIntegerField(default=0)),
                ("output_key", models.CharField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error", models.TextField(blank=True, default="")),
            ],
        )
    ]
